[
    {
        name: 'Bagel and cream cheese',
        category: 'Breakfast',
        img: 'https://i.ibb.co/7JRD0Th/breakfast4.png',
        price: '6.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Breakfast sandwich',
        category: 'Breakfast',
        img: 'https://i.ibb.co/JprR4GX/breakfast2.png',
        price: '9.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Baked Chicken',
        category: 'Breakfast',
        img: 'https://i.ibb.co/58cgMQs/breakfast3.png',
        price: '10.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Egg Benedict',
        category: 'Breakfast',
        img: 'https://i.ibb.co/vQ4vRbf/breakfast1.png',
        price: '8.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Toast Crossant Fried egg',
        category: 'Breakfast',
        img: 'https://i.ibb.co/zN26XRm/breakfast6.png',
        price: '9.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Fried Egg Toast Brunch',
        category: 'Breakfast',
        img: 'https://i.ibb.co/Tg5SqK8/breakfast5.png',
        price: '11.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Healthy Meal Plan',
        category: 'Lunch',
        img: 'https://i.ibb.co/0cfbNdB/lunch6.png',
        price: '23.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Fried Chicken Bento',
        category: 'Lunch',
        img: 'https://i.ibb.co/9h1p3cK/lunch5.png',
        price: '9.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Tarragon Rubbed Salmon',
        category: 'Lunch',
        img: 'https://i.ibb.co/4FMfwv9/lunch3.png',
        price: '8.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Indian Lunch',
        category: 'Lunch',
        img: 'https://i.ibb.co/vQ9Ccn5/lunch4.png',
        price: '8.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Beef Steak',
        category: 'Lunch',
        img: 'https://i.ibb.co/pyzfrB3/lunch1.png',
        price: '15.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Salmon with Peppers',
        category: 'Lunch',
        img: 'https://i.ibb.co/gwtcFnb/lunch2.png',
        price: '7.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Salmon with Grapefruit',
        category: 'Dinner',
        img: 'https://i.ibb.co/bm170sY/dinner6.png',
        price: '9.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Lemony Salmon Piccata',
        category: 'Dinner',
        img: 'https://i.ibb.co/Y02BZBm/dinner2.png',
        price: '10.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Pork Tenderloin',
        category: 'Dinner',
        img: 'https://i.ibb.co/mG3Kd3j/dinner5.png',
        price: '12.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Garlic Butter Baked Salmon',
        category: 'Dinner',
        img: 'https://i.ibb.co/GtKmGnP/dinner3.png',
        price: '6.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'French fries with cheese',
        category: 'Dinner',
        img: 'https://i.ibb.co/9HdLmPk/dinner4.png',
        price: '8.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
    {
        name: 'Baked Chicken',
        category: 'Dinner',
        img: 'https://i.ibb.co/VBs88GX/dinner1.png',
        price: '9.99',
        slug: 'How to dream about your future',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. In ratione vitae explicabo autem excepturi perspiciatis vel, sunt esse accusamus nihil possimus voluptas ipsa quam aut exercitationem minus assumenda perferendis expedita quibusdam! Eaque ut consequuntur in omnis, mollitia doloremque magnam similique dicta optio, exercitationem assumenda quis. Tempore suscipit temporibus obcaecati impedit.',
    },
]